### ISSUE TITLE
When the plugin is enabled, the metadata editing interface freezes.

### ISSUE THREAD

**Issue by Druidblack** [HotMasya/jellyfin-plugin-hikka#2]
I've installed the plugin, and I'm trying to edit the metadata. But the interface doesn't load. I disabled the plugin, and the interface loaded.

**Comment by HotMasya** [comment]
What is your jellyfin version? It must be 10.10.3 or above

**Comment by Druidblack** [comment]
10.10.5 (docker)

**Comment by HotMasya** [comment]
omw to update jellyfin.

**Comment by HotMasya** [comment]
@Druidblack For some reason it works fine on 10.10.3, but not on 10.10.5. Actually I do have interface but some parts of interface doesn't work properly.

**Comment by HotMasya** [comment]
For some reason I cannot edit metadata and there are no particular errors in the console. I'll try to update jellyfin api version and see what I can do. But not today, unfortunately.

**Comment by HotMasya** [comment]
@Druidblack Updated libraries to the latest jellyfin version 10.10.6. Just checked release files. It seems to work now :)

**Comment by Druidblack** [comment]
the update did not help. I tried restarting jf several times. when the plugin is enabled, the metadata editing interface freezes.

**Comment by HotMasya** [comment]
I'm sorry

**Comment by Druidblack** [comment]
10.10.6
I didn't see any errors in the logs.

I have a hunch that maybe your plugin conflicts with one of the plugins that I have installed. I want to try disabling all plugins and leaving only yours. I'll write about the result.

**Comment by HotMasya** [comment]
It seems to be some kind of frontend bug 🤔 
But it happens only with my plugin 

```
Uncaught (in promise) TypeError: e.split is not a function
    t https://jellyfin.masya.moe/web/main.jellyfin.bundle.js?396e11c26ee7da0b4726:2
    translate https://jellyfin.masya.moe/web/main.jellyfin.bundle.js?396e11c26ee7da0b4726:2
    Y https://jellyfin.masya.moe/web/26855.dc7cddc9f610c7a5aa0e.chunk.js:1
    Y https://jellyfin.masya.moe/web/26855.dc7cddc9f610c7a5aa0e.chunk.js:1
    promise callback*Y https://jellyfin.masya.moe/web/26855.dc7cddc9f610c7a5aa0e.chunk.js:1
    show https://jellyfin.masya.moe/web/26855.dc7cddc9f610c7a5aa0e.chunk.js:1
    show https://jellyfin.masya.moe/web/26855.dc7cddc9f610c7a5aa0e.chunk.js:1
```

**Comment by Druidblack** [comment]
Disabling all plugins did not help.

**Comment by diachenkomaks** [comment]
Yeah, I know. I'll try to start `jellyfin-web` client from repo and debug where the issue comes from, since all sources are minified.

**Comment by diachenkomaks** [comment]
I found the issue. Pushing changes...

**Comment by HotMasya** [comment]
It was an issue of my external provider invalid definition. Should work fine right now. At least I'm now able to open metadata editor and metadata window for specific series or movie.
